name: Checks

on:
    pull_request:
    push:

jobs:
    web-checks:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: 22

            - name: Setup Bun
              uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest

            - name: Install dependencies
              run: bun install

            - name: Sync SvelteKit # (generates .svelte-kit/tsconfig.json)
              run: cd web && bunx svelte-kit sync

            - name: Lint
              run: bun run web:lint extension:lint

            - name: Typecheck
              run: bun run web:check extension:check
